import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import React, { useState, useEffect } from "react";

export default function Home(props) {
  const [user, updatetUser] = useState("61ac9e5106c30a142800b5a1");
  const [postForm, updatePostForm] = useState({
    title: "",
    hashedSecret: "",
    userId: user,
  });
  const [getForm, updateGetForm] = useState({
    secretId: "61b457c8b2e2500b36e0dfb4",
    userId: user,
  });
  const [secret, updateSecret] = useState("");
  useEffect(() => {
    // storing input name
    if (!localStorage.getItem("userId")) {
      localStorage.setItem("userId", JSON.stringify("61ac9e5106c30a142800b5a1"));
    }
  });

  const inputChangeHandler = (e) => {
    let inId = e.target.id;
    let value = e.target.value;
    console.log(e.target.parentNode.id);
    if (e.target.parentNode.id === "readForm") {
      updateGetForm((oldForm) => {
        console.log(getForm);
        return { ...oldForm, [inId]: value };
      });
    } else if (e.target.parentNode.id === "writeForm") {
      updatePostForm((oldForm) => {
        console.log(postForm);
        return { ...oldForm, [inId]: value };
      });
    }

    console.log(postForm);
  };
  const readRecord = (e) => {
    e.preventDefault();
    const requestOptions = {
      method: "GET",
      headers: { "Content-Type": "application/json" },
      // body: JSON.stringify({ getForm }),
    };
    fetch(`http://localhost:3000/api/secrets/?userId=${encodeURIComponent(getForm.userId)}&secretId=${encodeURIComponent(getForm.secretId)}`, requestOptions)
      .then((response) => response.json())
      .then((data) => {
        console.log(data);
        updateSecret(data.data[0].hashedSecret);
        updateGetForm({
          secretId: "",
          userId: user,
        });
      });
  };
  const addRecord = (e) => {
    e.preventDefault();
    const requestOptions = {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ postForm }),
    };
    fetch("http://localhost:3000/api/secrets", requestOptions)
      .then((response) => response.json())
      .then((data) => {
        console.log(data);
        updatePostForm({
          title: "",
          hashedSecret: "",
          userId: "",
        });
      });
  };
  const clickHandler = (e) => {
    e.preventDefault();
    console.log(e.target.childNodes[0].textContent);
    updateGetForm((oldForm) => {
      return { ...oldForm, secretId: e.target.childNodes[0].textContent };
    });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>The Crypt</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          You just entered <a>The Crypt!</a>
        </h1>
        <p className={styles.description}>
          <code className={styles.code}>Add your secrets and secure them</code>
        </p>
        Write:
        <form id="writeForm">
          <label htmlFor="title">Title:</label>
          <input type="text" value={postForm.title} name="title" id="title" onChange={inputChangeHandler} />
          <label htmlFor="secret">Secret:</label>
          <input type="text" value={postForm.hashedSecret} name="hashedSecret" id="hashedSecret" onChange={inputChangeHandler} />
          {/* <label htmlFor="userId">User ID:</label>
          <input type="text" value={postForm.userId} name="userId" id="userId" onChange={inputChangeHandler} /> */}
          <input type="button" value="Add" onClick={addRecord} />
        </form>
        <br />
        Read:
        <form id="readForm">
          <label htmlFor="title">Secret ID:</label>
          <input type="text" value={getForm.secretId} name="secretId" id="secretId" onChange={inputChangeHandler} style={{ width: "250px" }} />
          {/* <label htmlFor="hashedSecret">Secret:</label>
          <input type="text" value={getForm.hashedSecret} name="hashedSecret" id="hashedSecret" onChange={inputChangeHandler} /> */}
          {/* <label htmlFor="userId">User ID:</label>
          <input type="text" value={getForm.userId} name="userId" id="userId" onChange={inputChangeHandler} /> */}
          <input type="button" value="Read" onClick={readRecord} />
        </form>
        <p>Secret is: "{secret}"</p>
        <br />
        User ID: {user}
        <table className="tg">
          <thead>
            <tr>
              <th className="tg-t2cw">#</th>
              <th className="tg-t2cw">Title</th>
              <th className="tg-t2cw">Secret ID</th>
              <th className="tg-t2cw">Hashed Secret</th>
              <th className="tg-t2cw">User ID</th>
            </tr>
          </thead>
          <tbody>
            {props.value.map((dt, k) => {
              return (
                <tr key={k}>
                  <td className="tg-amwm">#{k + 1}</td>
                  <td className="tg-baqh">{dt.title}</td>
                  <td className="tg-baqh selectable" onClick={clickHandler}>
                    {dt._id}
                    <span className="tooltiptext">Select</span>
                  </td>
                  <td className="tg-baqh">{dt.hashedSecret}</td>
                  <td className="tg-baqh">{dt.userId}</td>
                </tr>
              );
            })}
          </tbody>
        </table>
        <br />
      </main>

      <footer className={styles.footer}>
        <a>
          Powered by AC{" "}
          {/* <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span> */}
        </a>
      </footer>
    </div>
  );
}

export const getStaticProps = async () => {
  const res = await fetch(`http://localhost:3000/api/secretList/?userId=${"61ac9e5106c30a142800b5a1"}`, {
    method: "GET",
    headers: {
      "Content-Type": "application/json",
    },
  });
  const posts = await res.json();
  console.log(posts);
  return {
    props: {
      value: posts.data,
    },
  };
};
